"""add_locations_and_characteristics

Revision ID: 3d9415095a7d
Revises: 32d4d30d6ac1
Create Date: 2026-02-23 00:06:22.712558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9415095a7d'
down_revision: Union[str, None] = '32d4d30d6ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('locations', sa.Text(), nullable=True))
    op.add_column('animals', sa.Column('temperament', sa.Text(), nullable=True))
    op.add_column('animals', sa.Column('lifespan', sa.String(length=100), nullable=True))
    op.add_column('animals', sa.Column('weight', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'weight')
    op.drop_column('animals', 'lifespan')
    op.drop_column('animals', 'temperament')
    op.drop_column('animals', 'locations')
    # ### end Alembic commands ###
