"""remove_diet_habitat

Revision ID: a6255a658dc9
Revises: 3d9415095a7d
Create Date: 2026-02-24 23:58:12.182938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6255a658dc9'
down_revision: Union[str, None] = '3d9415095a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'habitat')
    op.drop_column('animals', 'diet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('diet', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('animals', sa.Column('habitat', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
